fastlane_version '2.53.1'

before_all do
  ensure_git_branch
  ensure_git_status_clean
  git_pull
end

platform :ios do
   # iOS Lanes
   desc 'Fetch certificates and provisioning profiles'
   lane :certificates do
       match(app_identifier: 'com.niwsah.simplekeep', type: 'development', readonly: true)
       match(app_identifier: 'com.niwsah.simplekeep', type: 'appstore', readonly: true)
   end

   desc 'Build the iOS application.'
   private_lane :build do
     certificates
     gym(scheme: 'name', project: './ios/SimpleKeep.xcworkspace')
   end

   desc 'Ship to Testflight.'
   lane :beta do
    build
    pilot
    commit_version_bump(message: 'Bump build', xcodeproj: './ios/SimpleKeep.xcodeproj')
    push_to_git_remote
   end
end

platform :android do
  # Android Lanes
end
